-- MySQL Script generated by MySQL Workbench
-- Monday 29 February 2016 01:57:00 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`game` ;

CREATE TABLE IF NOT EXISTS `mydb`.`game` (
  `id` INT NULL DEFAULT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teams` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(256) NOT NULL,
  `created_on` VARCHAR(30) NOT NULL,
  `services_ports_low` INT NOT NULL,
  `services_ports_high` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`id` ASC),
  UNIQUE INDEX `services_ports_low_UNIQUE` (`services_ports_low` ASC),
  UNIQUE INDEX `services_ports_high_UNIQUE` (`services_ports_high` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`services` ;

CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `internal_port` INT NOT NULL,
  `description` TEXT NOT NULL,
  `authors` VARCHAR(2048) NOT NULL,
  `flag_id_description` VARCHAR(2048) NOT NULL,
  `created_on` VARCHAR(30) NOT NULL,
  `offset_external_container_port` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`id` ASC),
  UNIQUE INDEX `offset_external_port_UNIQUE` (`offset_external_container_port` ASC),
  UNIQUE INDEX `internal_port_UNIQUE` (`internal_port` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`team_service_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`team_service_state` ;

CREATE TABLE IF NOT EXISTS `mydb`.`team_service_state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) NOT NULL,
  `service_id` INT(11) NOT NULL,
  `state` TINYINT(2) NOT NULL,
  `reason` VARCHAR(256) NOT NULL,
  `created_on` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`team_id` ASC, `service_id` ASC),
  INDEX (`team_id` ASC),
  INDEX (`state` ASC),
  INDEX (`team_id` ASC, `service_id` ASC, `created_on` ASC),
  INDEX (`state` ASC, `team_id` ASC, `service_id` ASC, `created_on` ASC),
  INDEX `fk_team_service_state_service_id_idx` (`service_id` ASC),
  CONSTRAINT `fk_team_service_state_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_service_state_service_id`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`team_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`team_score` ;

CREATE TABLE IF NOT EXISTS `mydb`.`team_score` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) NOT NULL,
  `score` INT NOT NULL,
  `reason` VARCHAR(256) NOT NULL,
  `created_on` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`team_id` ASC),
  INDEX (`created_on` ASC),
  CONSTRAINT `fk_team_score_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`exploit_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`exploit_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`exploit_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_id` INT(11) NOT NULL,
  `defending_team_id` INT(11) NOT NULL,
  `attacking_team_id` INT(11) NOT NULL,
  `is_attack_success` TINYINT(1) NOT NULL,
  `exploit_stdout` VARCHAR(2048) NULL,
  `exploit_stderr` VARCHAR(2048) NULL,
  `created_on` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`is_attack_success` ASC),
  INDEX (`created_on` ASC),
  INDEX (`defending_team_id` ASC, `service_id` ASC, `created_on` ASC),
  INDEX `fk_exploit_status_service_id_idx` (`service_id` ASC),
  INDEX `fk_exploit_status_attacker_id_idx` (`attacking_team_id` ASC),
  CONSTRAINT `fk_exploit_status_service_id`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exploit_status_defender_id`
    FOREIGN KEY (`defending_team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exploit_status_attacker_id`
    FOREIGN KEY (`attacking_team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`script_runs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`script_runs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`script_runs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `operation` ENUM('STOREFLAG', 'RETRFLAG') NOT NULL,
  `target_team_id` INT(11) NOT NULL,
  `error` INT(11) NOT NULL,
  `error_msg` VARCHAR(2048) NULL DEFAULT NULL,
  `stdout` VARCHAR(2048) NULL,
  `stderr` VARCHAR(2048) NULL,
  `created_on` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_script_runs_team_id_idx` (`target_team_id` ASC),
  CONSTRAINT `fk_script_runs_team_id`
    FOREIGN KEY (`target_team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`flags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) NOT NULL,
  `service_id` INT(11) NOT NULL,
  `flag` VARCHAR(128) NOT NULL,
  `flag_id` VARCHAR(128) NULL DEFAULT NULL,
  `cookie` VARCHAR(128) NULL DEFAULT NULL,
  `created_on` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`flag` ASC),
  INDEX (`team_id` ASC),
  INDEX (`service_id` ASC),
  INDEX (`team_id` ASC, `service_id` ASC),
  INDEX (`created_on` ASC),
  CONSTRAINT `fk_flags_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flags_service_id`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`flag_submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flag_submission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flag_submission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) NOT NULL,
  `flag` VARCHAR(128) NOT NULL,
  `submitted_at` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`team_id` ASC),
  INDEX (`flag` ASC),
  UNIQUE INDEX (`team_id` ASC, `flag` ASC),
  INDEX (`submitted_at` ASC),
  CONSTRAINT `fk_flag_submission_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flag_submission_flag`
    FOREIGN KEY (`flag`)
    REFERENCES `mydb`.`flags` (`flag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`ticks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ticks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ticks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time_to_change` VARCHAR(30) NOT NULL,
  `created_on` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`created_on` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`containers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`containers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`containers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `team_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `type` ENUM('SERVICE', 'EXPLOIT') NOT NULL,
  `update_required` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`full_name` ASC),
  INDEX `fk_containers_team_id_idx` (`team_id` ASC),
  INDEX `fk_containers_service_id_idx` (`service_id` ASC),
  CONSTRAINT `fk_containers_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_containers_service_id`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services_locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`services_locations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`services_locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `host_ip` VARCHAR(45) NOT NULL,
  `host_port` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_services_locations_team_id_idx` (`team_id` ASC),
  INDEX `fk_services_locations_service_id_idx` (`service_id` ASC),
  CONSTRAINT `fk_services_locations_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_services_locations_service_id`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
